### ISSUE TITLE
Selecting an option does not add it immediately to v-model's textarea

### ISSUE THREAD

**Issue by gusMoreno** [fritx/vue-at#100]
Hi, 

My application has a chat, and I am using at-textarea to select tags and users. I based my code in the demonstration available in the FAQ page.

Here is my code:
![Captura de Tela 2019-05-14 às 12 52 35](https://user-images.githubusercontent.com/6085835/57713673-527b1900-7649-11e9-9073-5a455ee716b3.png)

The issue is that when I select an option, the option is not added immediately to the v-model `newMessage`. It even shows in the textarea, but it only gets added to `newMessage` if/when I type anything else. The gif below demonstrates the issue:
![vue-at gif](https://user-images.githubusercontent.com/6085835/57713838-a38b0d00-7649-11e9-85b4-4430b482fd39.gif)

How can I fix this? 

Thanks in advance!

**Comment by fritx** [comment]
@gusMoreno try v-model on `<at-ta>` instead of `<textarea>`, see
readme: https://github.com/fritx/vue-at#using-v-model-recommended
docs: https://fritx.github.io/vue-at/#/en/vmodel

**Comment by gusMoreno** [comment]
@fritx Thanks for replying!

I tried everything in the docs. Doing it does not update the `newMessage` value. I even removed one of the `<at>` components, as per code below, but it does not work:

![Captura de Tela 2019-05-16 às 09 06 57](https://user-images.githubusercontent.com/6085835/57852628-056a8480-77ba-11e9-8e96-eaf8c8cd737a.png)

Here is a gif, showing that even though the textarea is changing, the `newMessage` is always equals an empty string.

![gif2](https://user-images.githubusercontent.com/6085835/57852854-a48f7c00-77ba-11e9-9678-329166b3e626.gif)

**Comment by gusMoreno** [comment]
@fritx Is there a workaround to this issue? I can provide more documentation if necessary.

**Comment by fritx** [comment]
@gusMoreno is there any third-party library that processes the textarea?
like https://github.com/fritx/vue-at#used-with-3rd-party-libraries

It should be working if you at least use the latest version of vue-at, 2.5.0-beta.2, try it plz

**Comment by gusMoreno** [comment]
@fritx It was not a third-party library, just a regular textarea. It worked after upgrading the vue-at version to 2.5.0-beta.2

Thank you, I really appreciate your support, and the work you are doing with vue-at!!

**Comment by zisan34** [comment]
Still having this issue. Exactly the same as @gusMoreno for me this didn't solve by moving to 2.5.0-beta.2

**Comment by zisan34** [comment]
Still having this issue. Exactly the same as @gusMoreno for me this didn't solve by moving to 2.5.0-beta.2
https://prnt.sc/ui1w4r

the data is entered to v-model after the user hits another key after selecting the mention. For example, if I select a mention then make another keypress then it works. Otherwise doesn't.
https://prnt.sc/ui1va4
